<?php

function my_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if($form_id == 'comment_comment_form'){
        $form['actions']['submit']['#value'] = t('Comment');
    }
}
function my_module_preprocess_webform_confirmation(&$vars) {
  if ($vars['webform']->id() == 'site_form') {
    $request = \Drupal::request()->query;
    $display_mode = $request->get('display_mode');
    $rate_type = $request->get('rate_type');
    if ($rate_type === 'complete' && $display_mode === 'overlay') {
      $markup = t('Thank you for sharing with us your opinions about our website!') . '<br/><br/>';
      $markup .= '<button class="overlay-only">';
      $markup .= t('Explore more of this game site');
      $markup .= '</button>';
      $vars['message']['#allowed_tags'] = ['br', 'button'];
    }
    else {
      $markup = t('Thank you for sharing with us your opinions about our website!');
    }

    $vars['message']['#markup'] = $markup;
  }
}


// hook_form_FORM_ID_alter()
//hook_webform_handler_invoke_pre_create_alter
//hook_webform_handler_invoke_pre_save_alter

//function my_module_webform_handler_invoke_pre_create_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
function my_module_form_site_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
//function my_module_webform_handler_invoke_pre_save_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'site_form') {
    //if ($form('#webform_id') == 'site_form') {
    $current_user = \Drupal::currentUser();
    $user_email = $current_user->getEmail();
    //die(dump($user_email));
    // var_dump($user_email);
    // die();
     $form['submitted']['email']['#default_value'] = $user_email;
   // $form['submitted']['field_email']['#default_value'] = $user_email;
    if(!$current_user->isAnonymous()) {
      //$form['submitted']['field_email']['#default_value']= t('anynomous@abv.bg');
      // $form['submitted']['field_email']['#default_value']= 'anynomous@abv.bg';
      //$form['submitted']['email']['#default_value']= 'anynomous@abv.bg';
      $form['submitted']['email']['#default_value']= t('anynomous@abv.bg');
    }
  }
}
